apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pharma-ui
  namespace: dev
  labels:
    app: pharma-ui
    version: "1.0.0"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: a60d56049241343ed8396d21db56adc7-38bc3556c3844687.elb.us-east-1.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pharma-ui
                port:
                  number: 80
